const { defineConfig } = require("cypress");

module.exports = defineConfig({
  animationDistanceThreshold: 5,
  chromeWebSecurity: true,
  defaultCommandTimeout: 4000,
  downloadsFolder: "cypress/downloads",
  e2e: {
    baseUrl: "https://www.google.com",
    supportFile: "cypress/support/index.js",
    specPattern: "**/*.*",
},
  execTimeout: 60000,
  experimentalFetchPolyfill: false,
  experimentalInteractiveRunEvents: false,
  experimentalSessionAndOrigin: false,
  experimentalSourceRewriting: false,
  experimentalStudio: false,
  fileServerFolder: "",
  includeShadowDom: false,
  keystrokeDelay: 0,
  modifyObstructiveCode: true,
  numTestsKeptInMemory: 50,
  pageLoadTimeout: 60000,
  port: null,
  projectId: null,
  redirectionLimit: 20,
  reporter: "spec",
  reporterOptions: null,
  requestTimeout: 5000,
  resolvedNodePath: null,
  resolvedNodeVersion: null,
  responseTimeout: 30000,
  screenshotOnRunFailure: true,
  screenshotsFolder: "cypress/screenshots",
  scrollBehavior: "top",
  supportFolder: false,
  taskTimeout: 60000,
  trashAssetsBeforeRuns: true,
  userAgent: null,
  video: true,
  videoCompression: 32,
  videosFolder: "cypress/videos",
  videoUploadOnPasses: true,
  viewportHeight: 660,
  viewportWidth: 1000,
  waitForAnimations: true,
  watchForFileChanges: true,
  hosts: null,
  isInteractive: true,
});
